/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2013-09-20 12:05:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class right_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/jquery-1.5.2.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/jquery.history.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/raphael.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/vis4.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/jslib/Tween.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/build/bubbletree.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./BubbleTree/build/bubbletree.css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"./BubbleTree/styles/cofog.js\"></script>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("        $(function() {\n");
      out.write("\n");
      out.write("\n");
      out.write("            var data = {\n");
      out.write("                label: '神戸情報大学院大学',\n");
      out.write("                amount: 20,\n");
      out.write("                children: [\n");
      out.write("                    { label: '1st', amount: 10, color: '#D95F02',\n");
      out.write("                        children: [\n");
      out.write("                        { label: '13', amount: 1, color: '#D95F02' },\n");
      out.write("                        { label: '11', amount: 1, color: '#D95F02' },\n");
      out.write("                        { label: '17', amount: 1, color: '#D95F02' },\n");
      out.write("                        { label: '25', amount: 1, color: '#D95F02' },\n");
      out.write("                        { label: '15', amount: 1, color: '#D95F02' },\n");
      out.write("                        { label: '12', amount: 1, color: '#D95F02' },\n");
      out.write("                        { label: '14', amount: 1, color: '#D95F02' },\n");
      out.write("                        { label: '18', amount: 1, color: '#D95F02' },\n");
      out.write("                        { label: '19', amount: 1, color: '#D95F02' },\n");
      out.write("                        { label: '20', amount: 1, color: '#D95F02' },\n");
      out.write("\n");
      out.write("                    ] },\n");
      out.write("                    { label: '神戸', amount: 2, color: '#1B9E77',\n");
      out.write("                        children: [\n");
      out.write("                        { label: '1', amount: 1, color: '#1B9E77' },\n");
      out.write("                        { label: '5', amount: 1, color: '#1B9E77' }\n");
      out.write("                    ]\n");
      out.write("                    },\n");
      out.write("                    { label: '情報', amount: 2, color: '#7570B3',\n");
      out.write("                        children: [\n");
      out.write("                        { label: '2', amount: 5, color: '#7570B3' },\n");
      out.write("                        { label: '3', amount: 8, color: '#7570B3'}\n");
      out.write("                    ]\n");
      out.write("                    }\n");
      out.write("                ]\n");
      out.write("            };\n");
      out.write("\n");
      out.write("            new BubbleTree({\n");
      out.write("                data: data,\n");
      out.write("                bubbleType: 'icon',\n");
      out.write("                container: '.bubbletree'\n");
      out.write("            });\n");
      out.write("\n");
      out.write("        });\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"bubbletree-wrapper\">\n");
      out.write("<div class=\"bubbletree\"></div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
